#!/bin/bash
tab=('')
let "i=0"
let "c=0"
twc="`cat /etc/fstab | grep -v '^#' | grep 'ext'`"
for p in $twc
do
	let "b=i%6"
	if [ $b -eq 0 ]
	then
		t="`echo $p | cut -c 1-5`"
		if [ $t = "UUID=" ] || [ $t = "LABEL" ]
		then
			z="`findfs $p`"
			tab[$c]=$z
			let "c+=1"
		else
		       	tab[$c]=$p
			let "c+=1"
		fi
	fi
	let "i+=1"
done
ListeFS="${tab[*]}"
for element in $ListeFS
do
	if (mdadm --detail $element |grep "raid1" ) > /dev/null 2>&1
	then
		nbsm=$(mdadm --detail $element|grep "active"|awk '{print $NF}'|wc -l) 
		if [ $nbsmi -gt 1 ]
		then
			ListeRaid1=${ListeRaid1}" $element "$(mdadm --detail $element|grep "active"|awk '{print $NF}'|tail -l)
		else
			echo -e "PROBLEME pour $element \nLe nombre \
				de sous-miroirs est insuffisant." >> ${FicLog}
			MesPB=$MesPB"\nSauvegarde de $element non realisee: \
                probleme sur sa configuration."
		fi
	fi
echo $ListeRaid1
